name: web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  convert: ^3.1.1
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/fondo_splash.png
    - assets/image/LOGO_INTRANT.png
    - assets/image/LOGO_PARQUEATE.png

flutter_native_splash:
  android: false
  web: true
  ios: false
  color: 
  image: assets/image/LOGO_PARQUEATE.png
  background_image: assets/image/fondo_splash.png
  branding: "assets/image/LOGO_INTRANT.png"
  branding_mode: bottom
 

