name: frontend_android
description: "demo_orintek"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.1
  geolocator: ^11.0.0
  http: ^1.2.1
  image_picker: ^1.0.7
  permission_handler: ^11.3.1
  logger: ^2.2.0
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  wed: false
  image_path: "assets/ic_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/splash/back.png
    - assets/splash/bottom.png
    - assets/splash/main.png
    - assets/launcher_android_12+/main_splash.png
    - assets/launcher_android_-11/ic_icon.png
    - assets/whiteback/main_w.png
    - assets/icons/photo.svg
    - assets/icons/add.svg
